name: "pkgs"

runs:

  using: "composite"

  steps:

  - uses: actions/setup-python@v5
    with:
      python-version: '3.13'

  - name: Python pkgs
    shell: bash
    run: pip install numpy h5py

  - name: install HDF5 (Linux)
    shell: bash
    if: runner.os == 'Linux'
    run: |
      sudo apt update
      sudo apt install --no-install-recommends libhdf5-dev

  - name: Install HDF5 (MacOS)
    shell: bash
    if: runner.os == 'macOS'
    run: brew install hdf5
