name: ci_linux

on:
  push:
    paths:
      - "**.build"
      - "**.txt"
      - "**.cmake"
      - "**.f90"
      - ".github/workflows/ci_linux.yml"
  pull_request:
    paths:
      - "**.build"
      - "**.txt"
      - "**.cmake"
      - "**.f90"
      - ".github/workflows/ci_linux.yml"

jobs:

  linuxMeson:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - run: pip install -r requirements.txt
    - run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends ninja-build gfortran libhdf5-dev

    - run: meson setup build
      env:
        FC: gfortran

    - run: ninja -C build

    # this catches configuration and build log
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_Meson_Buildlog
        path: build/meson-logs/meson-log.txt

    - run: meson test -C build -v
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_Meson_Testlog
        path: build/meson-logs/testlog.txt

  linuxCmake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - run: |
        pip install cmake
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran libhdf5-dev

    - name: CMake configure
      run: cmake -B build
      env:
        FC: gfortran
    - run: cmake --build build --parallel
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_CMake_Buildlog
        path: build/CMakeFiles/CMakeError.log

    - run: ctest -V
      working-directory: build
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_CMake_Testlog
        path: build/Testing/Temporary/LastTest.log
