name: ci_linux

on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - "**.f90"
      - ".github/workflows/ci_linux.yml"

jobs:

  cmake:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran libhdf5-dev

    - run: ctest -S setup.cmake -VV

    - name: build examples
      run: |
        cmake -B Examples/build -S Examples
        cmake --build Examples/build

    - name: test examples
      run: ctest -V
      working-directory: Examples/build

  build_hdf5:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: ctest -S setup.cmake -VV
      env:
        FC: gfortran-9
        CC: gcc-9
