name: ci_mac_meson

on:
  push:
    paths:
      - "**.build"
      - ".github/workflows/ci_mac_meson.yml"

jobs:

  meson:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: pip install meson
    - run: brew install pkg-config hdf5 ninja

    - run: meson setup build
      env:
        FC: gfortran-9
        CC: gcc-9

    - run: ninja -C build
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Mac_Meson_Buildlog
        path: build/meson-logs/meson-log.txt

    - run: meson test -C build -v
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Mac_Meson_Testlog
        path: build/meson-logs/testlog.txt
