name: ci_mac

on:
  push:
    paths:
      - "**.build"
      - "**.txt"
      - "**.cmake"
      - "**.f90"
      - ".github/workflows/ci_mac.yml"
  pull_request:
    paths:
      - "**.build"
      - "**.txt"
      - "**.cmake"
      - "**.f90"
      - ".github/workflows/ci_mac.yml"

jobs:

  macMeson:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - run: pip install -r requirements.txt
    - run: brew install pkg-config gcc hdf5 ninja

    - run: meson setup build
      env:
        FC: gfortran-9
        CC: gcc-9

    - run: ninja -C build
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Mac_Meson_Buildlog
        path: build/meson-logs/meson-log.txt

    - run: meson test -C build -v
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Mac_Meson_Testlog
        path: build/meson-logs/testlog.txt

  macCmake:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: brew install pkg-config gcc hdf5
    - run: cmake -B build
      env:
        FC: gfortran-9
        CC: gcc-9

    - run: cmake --build build --parallel
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Mac_CMake_Buildlog
        path: build/CMakeFiles/CMakeError.log

    - run: ctest -V
      working-directory: build
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Mac_CMake_Testlog
        path: build/Testing/Temporary/LastTest.log