name: ci_macos

env:
  CTEST_PARALLEL_LEVEL: 4
  CMAKE_BUILD_TYPE: Release
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  FC: gfortran-11

on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - "**.f90"
      - ".github/workflows/ci_macos.yml"
  release:
    types: [published]

jobs:

  macos:
    runs-on: macos-latest
    timeout-minutes: 20

    strategy:
      matrix:
        shared: [true, false]

    steps:

    - run: brew install hdf5 ninja

    - uses: actions/checkout@v2

    - run: cmake --preset multi -DCMAKE_INSTALL_PREFIX=${{ runner.temp }} -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}

    - run: cmake --build --preset debug
    - run: ctest --preset debug

    - run: cmake --build --preset release
    - run: ctest --preset release

    - run: cmake --install build

    - name: configure examples
      run: cmake -S Examples -B Examples/build -DCMAKE_PREFIX_PATH:PATH=${{ runner.temp }} -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}
    - name: build Examples
      run: cmake --build Examples/build --parallel
    - name: Test Examples
      run: ctest --test-dir Examples/build -V


  macos-build:
    needs: macos
    runs-on: macos-latest
    timeout-minutes: 20

    strategy:
      matrix:
        shared: [true, false]

    steps:

    - uses: actions/checkout@v2

    - name: Configure HDF5
      run: cmake -S scripts -B scripts/build -DCMAKE_INSTALL_PREFIX=${{ runner.temp }} -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}

    - name: Build/install HDF5
      run: cmake --build scripts/build --parallel

    - run: cmake -B build -DCMAKE_INSTALL_PREFIX=${{ runner.temp }} -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }} -DCMAKE_PREFIX_PATH=${{ runner.temp }}
    - run: cmake --build build --parallel
    - run: ctest --test-dir build --preset default
    - run: cmake --install build

    - name: configure examples
      run: cmake -S Examples -B Examples/build -DCMAKE_PREFIX_PATH:PATH=${{ runner.temp }} -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}
    - name: build Examples
      run: cmake --build Examples/build --parallel
    - name: Test Examples
      run: ctest --test-dir Examples/build -V
