name: ci_mac

on:
  push:
    paths:
      - "**.txt"
      - "**.cmake"
      - "**.f90"
      - ".github/workflows/ci_mac.yml"
  pull_request:


jobs:

  cmake:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - run: brew install pkg-config hdf5 ninja

    - run: ctest -S setup.cmake -V
      env:
        FC: gfortran-9
        CC: gcc-9
