name: ci_macos

env:
  CTEST_PARALLEL_LEVEL: 3
  CMAKE_BUILD_PARALLEL_LEVEL: 3
  CMAKE_BUILD_TYPE: Release
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  FC: gfortran-11

on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - "**.f90"
      - ".github/workflows/ci_macos.yml"
  release:
    types: [published]

jobs:

  mac-static:
    runs-on: macos-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v2

    - run: brew install hdf5 ninja

    - run: cmake --preset multi --install-prefix=${HOME}
    - run: cmake --build --preset debug
    - run: ctest --preset debug

    - run: cmake --build --preset release
    - run: ctest --preset release

    - run: cmake --install build

    - run: cmake -S Examples -B Examples/build -Dh5fortran_ROOT=~
    - run: cmake --build Examples/build
    - run: ctest --test-dir Examples/build --output-on-failure

    - name: create package
      if: github.event.action == 'published'
      run: cpack --config build/CPackConfig.cmake

    - name: Upload artifact
      if: github.event.action == 'published'
      uses: actions/upload-artifact@v1
      with:
        name: binary-archive
        path: build/package

    - name: get version
      if: github.event.action == 'published'
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

    - name: Upload release asset
      if: github.event.action == 'published'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: build/package/h5fortran-${{ steps.get_version.outputs.VERSION }}-Darwin.tar.zst
        asset_name:  h5fortran-${{ steps.get_version.outputs.VERSION }}-Darwin.tar.zst
        asset_content_type: application/zip


  mac-shared:
    needs: mac-static
    runs-on: macos-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v2

    - run: brew install hdf5 ninja

    - run: cmake --preset multi -DBUILD_SHARED_LIBS:BOOL=true --install-prefix=${HOME}
    - run: cmake --build --preset debug
    - run: ctest --preset debug

    - run: cmake --build --preset release
    - run: ctest --preset release

    - run: cmake --install build

    - run: cmake -S Examples -B Examples/build -Dh5fortran_ROOT=~
    - run: cmake --build Examples/build
    - run: ctest --test-dir Examples/build --output-on-failure


  mac-build-static:
    needs: mac-static
    runs-on: macos-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v2

    - run: cmake -B build --preset build --install-prefix=${HOME}
    - run: cmake --build build
    - run: ctest --test-dir build --preset default
    - run: cmake --install build


  mac-build-shared:
    needs: [mac-shared, mac-build-static]
    runs-on: macos-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v2

    - run: cmake -B build --preset build -DBUILD_SHARED_LIBS=on --install-prefix=${HOME}
    - run: cmake --build build
    - run: ctest --test-dir build --preset default
    - run: cmake --install build
