name: ci_mac

on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".github/workflows/ci_mac.yml"

jobs:

  cmake:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - run: brew install pkg-config hdf5 ninja

    - run: ctest -S setup.cmake -V
      env:
        FC: gfortran-9
        CC: gcc-9

    - name: build examples
      run: |
        cmake -B Examples/build -S Examples
        cmake --build Examples/build

    - name: test examples
      run: ctest -V
      working-directory: Examples/build
